Repository apache/apisix-ingress-controller, pull requests merged in 2021-11, with the labels that each got.

#757 docs: update proxy-the-httpbin-service.md
  docs/en/latest/practices/proxy-the-httpbin-service.md
Labels: documentation

#755 feat: support https and grpcs as upstream scheme as well as mTLS mode
  Makefile
  go.sum
  pkg/kube/apisix/apis/config/v1/types.go
  pkg/kube/apisix/apis/config/v1/zz_generated.deepcopy.go
  pkg/kube/translation/apisix_upstream.go
  pkg/kube/translation/translator.go
  pkg/types/apisix/v1/types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  samples/deploy/crd/v1/ApisixUpstream.yaml
  test/e2e/features/scheme.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/ingress/upstream_tls.go
  test/e2e/plugins/uri_blocker.go
  test/e2e/scaffold/scaffold.go
  test/e2e/scaffold/test_backend.go
  test/e2e/scaffold/upstream_tls.go
  test/e2e/testbackend/Dockerfile
  test/e2e/testbackend/client/client.go
  test/e2e/testbackend/go.mod
  test/e2e/testbackend/go.sum
  test/e2e/testbackend/main.go
  test/e2e/testbackend/tls/ca.pem
  test/e2e/testbackend/tls/client.key
  test/e2e/testbackend/tls/client.pem
  test/e2e/testbackend/tls/server.key
  test/e2e/testbackend/tls/server.pem
Labels: enhancement

#760 fix: If resource synchronization retry occurs, other events of the same resource will be blocked.
  pkg/ingress/apisix_cluster_config.go
  pkg/ingress/apisix_consumer.go
  pkg/ingress/apisix_route.go
  pkg/ingress/apisix_tls.go
  pkg/ingress/apisix_upstream.go
  pkg/ingress/endpoint.go
  pkg/ingress/endpointslice.go
  pkg/ingress/ingress.go
  pkg/ingress/namespace.go
  pkg/ingress/secret.go
Labels: bug
