Repository apache/apisix-ingress-controller, pull requests merged in 2021-09, with the labels that each got.

#627 feat: add metric 'check_cluster_health_total' and 'sync_operation_total'
  pkg/apisix/cluster.go
  pkg/ingress/apisix_consumer.go
  pkg/ingress/apisix_tls.go
  pkg/ingress/controller.go
  pkg/ingress/endpoint.go
  pkg/ingress/endpointslice.go
  pkg/ingress/secret.go
  pkg/metrics/prometheus.go
  pkg/metrics/prometheus_test.go
Labels: changelog

#687 fix: the fields in UpstreamPassiveHealthCheckUnhealthy should be timeouts
  pkg/apisix/schema.go
  pkg/kube/apisix/apis/config/v1/types.go
  pkg/kube/translation/apisix_upstream.go
  pkg/types/apisix/v1/types.go
  samples/deploy/crd/v1beta1/ApisixUpstream.yaml
Labels: bug, changelog

#693 feat: upgrade CRD version to v1
  Makefile
  README.md
  docs/en/latest/practices/check-crd-status.md
  docs/en/latest/practices/proxy-the-httpbin-service.md
  docs/en/latest/practices/the-hard-way.md
  samples/deploy/crd/v1/ApisixClusterConfig.yaml
  samples/deploy/crd/v1/ApisixConsumer.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  samples/deploy/crd/v1/ApisixTls.yaml
  samples/deploy/crd/v1/ApisixUpstream.yaml
  samples/deploy/crd/v1/kustomization.yaml
  samples/deploy/crd/v1beta1/ApisixConsumer.yaml
  samples/deploy/crd/v1beta1/ApisixRoute.yaml
  samples/deploy/crd/v1beta1/ApisixTls.yaml
  samples/deploy/crd/v1beta1/ApisixUpstream.yaml
  samples/deploy/kustomization.yaml
Labels: documentation, enhancement, changelog
