Repository apache/apisix-ingress-controller, pull requests merged in 2021-12, with the labels that each got.

#740 feat: Fix lb ingress status
  cmd/ingress/ingress.go
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ingress/apisix_route.go
  pkg/ingress/ingress.go
  pkg/ingress/status.go
  test/e2e/ingress/status.go
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/scaffold.go
Labels: area/controller

#780 fix: test case param error
  cmd/ingress/ingress_test.go
  pkg/api/router/router_test.go
  pkg/api/server_test.go
  pkg/apisix/cache/memdb_test.go
  pkg/apisix/consumer_test.go
  pkg/apisix/plugin_test.go
  pkg/apisix/route_test.go
  pkg/apisix/ssl_test.go
  pkg/apisix/upstream_test.go
  pkg/ingress/ingress_test.go
  pkg/ingress/manifest_test.go
  pkg/ingress/pod_test.go
  pkg/kube/translation/annotations/cors_test.go
  pkg/kube/translation/annotations/iprestriction_test.go
  pkg/kube/translation/apisix_consumer_test.go
  pkg/kube/translation/apisix_route_test.go
  pkg/kube/translation/apisix_upstream_test.go
  pkg/kube/translation/context_test.go
  pkg/kube/translation/ingress_test.go
  pkg/kube/translation/plugin_test.go
  pkg/kube/translation/translator_test.go
  pkg/kube/translation/util_test.go
  pkg/log/default_logger_test.go
  pkg/log/logger_test.go
  pkg/metrics/prometheus_test.go
  pkg/types/event_test.go
  pkg/types/labels_test.go
  pkg/types/pod_test.go
  pkg/types/timeduration_test.go
Labels: area/test

#777 Docs: add more config example
  docs/en/latest/deployments/ack.md
  docs/en/latest/deployments/aws.md
  docs/en/latest/deployments/azure.md
  docs/en/latest/deployments/gke.md
  docs/en/latest/deployments/kubesphere.md
  docs/en/latest/deployments/tke.md
Labels: documentation

#779 feat: support regex in path
  docs/en/latest/concepts/annotations.md
  pkg/kube/translation/annotations/cors.go
  pkg/kube/translation/annotations/iprestriction.go
  pkg/kube/translation/annotations/redirect.go
  pkg/kube/translation/annotations/rewrite.go
  pkg/kube/translation/annotations/types.go
  pkg/kube/translation/ingress.go
  pkg/kube/translation/ingress_test.go
  test/e2e/ingress/ingress.go
Labels: enhancement, changelog, triage/accepted

#772 feat: implement pluginconfig clients (#638)
  pkg/api/validation/apisix_route_test.go
  pkg/apisix/apisix.go
  pkg/apisix/cache/cache.go
  pkg/apisix/cache/memdb.go
  pkg/apisix/cache/memdb_test.go
  pkg/apisix/cache/schema.go
  pkg/apisix/cluster.go
  pkg/apisix/nonexistentclient.go
  pkg/apisix/pluginconfig.go
  pkg/apisix/pluginconfig_test.go
  pkg/apisix/resource.go
  pkg/apisix/schema.go
  pkg/types/apisix/v1/types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
Labels: area/controller

#794 fix: When the spec field of the ApisixUpstream resource is empty, it …
  pkg/ingress/apisix_upstream.go
  pkg/ingress/controller.go
  pkg/kube/translation/translator.go
Labels: bug

#805 docs(READEME.md): change image size
  README.md
Labels: documentation

#804 fix: some wrong or invalid logs
  pkg/ingress/ingress.go
Labels: triage/accepted

#789 feat: Initial support for Gateway API
  .github/workflows/e2e-test-ci.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-checker.yml
  .github/workflows/unit-test-ci.yml
  .github/workflows/verify-codegen.yml
  Dockerfile
  Makefile
  cmd/ingress/ingress.go
  conf/config-default.yaml
  docs/en/latest/aeps/0001-gateway-api.md
  docs/en/latest/aeps/README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/ingress/controller.go
  pkg/ingress/gateway.go
  pkg/ingress/status.go
  pkg/kube/apisix/client/clientset/versioned/fake/clientset_generated.go
  pkg/kube/init.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: enhancement, changelog

#815 feat: refactor ApisixPluginConfig and add e2e cases
  pkg/apisix/apisix.go
  pkg/apisix/cache/memdb.go
  pkg/apisix/cache/memdb_test.go
  pkg/apisix/cache/schema.go
  pkg/apisix/cluster.go
  pkg/apisix/cluster_test.go
  pkg/apisix/nonexistentclient.go
  pkg/ingress/apisix_pluginconfig.go
  pkg/ingress/apisix_route.go
  pkg/ingress/compare.go
  pkg/ingress/controller.go
  pkg/ingress/ingress.go
  pkg/ingress/manifest.go
  pkg/ingress/manifest_test.go
  pkg/ingress/status.go
  pkg/kube/apisix/apis/config/v2beta3/types.go
  pkg/kube/apisix/apis/config/v2beta3/zz_generated.deepcopy.go
  pkg/kube/apisix_plugin_config.go
  pkg/kube/apisix_route.go
  pkg/kube/translation/apisix_pluginconfig.go
  pkg/kube/translation/apisix_pluginconfig_test.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/apisix_route_test.go
  pkg/kube/translation/context.go
  pkg/kube/translation/context_test.go
  pkg/kube/translation/ingress.go
  pkg/kube/translation/ingress_test.go
  pkg/kube/translation/translator.go
  pkg/types/apisix/v1/types.go
  samples/deploy/crd/v1/ApisixPluginConfig.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  samples/deploy/rbac/apisix_view_clusterrole.yaml
  test/e2e/ingress/resourcepushing.go
  test/e2e/plugins/plugin_config.go
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/k8s.go
Labels: enhancement, area/controller

#731 docs: Grafana Dashboard Configuration
  docs/assets/images/dashboard_view_1.png
  docs/assets/images/dashboard_view_2.png
  docs/assets/images/dashboard_view_3.png
  docs/assets/images/datasource_1.png
  docs/assets/images/datasource_2.png
  docs/assets/images/grafana.png
  docs/assets/images/img.png
  docs/assets/images/import_via_panel_json.png
  docs/assets/images/metrics_data.png
  docs/assets/other/json/apisix-ingress-controller-grafana.json
  docs/en/latest/plugins/prometheus.md
Labels: documentation, triage/accepted
