Repository apache/apisix-ingress-controller, pull requests merged in 2022-12, with the labels that each got.

#1471 feat: add control http method using kubernetes ingress by annotations
  docs/en/latest/concepts/annotations.md
  go.mod
  go.sum
  pkg/providers/ingress/translation/annotations/plugins/http_method.go
  pkg/providers/ingress/translation/annotations/plugins/http_method_test.go
  pkg/providers/ingress/translation/annotations/plugins/plugins.go
  pkg/providers/ingress/translation/annotations/types.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite-annotations/http_method.go
Labels: area/controller

#1480 fix:sanitize log output when exposing sensitive values
  cmd/ingress/ingress.go
  cmd/ingress/ingress_test.go
Labels: area/controller

#1491 docs: fix typo
  docs/en/latest/concepts/apisix_upstream.md
Labels: documentation

#1479 doc: update upgrade guide
  docs/en/latest/upgrade.md
Labels: documentation

#1451 feat: ingress annotations supports the specified upstream schema
  docs/en/latest/concepts/annotations.md
  pkg/providers/ingress/translation/annotations.go
  pkg/providers/ingress/translation/annotations/types.go
  pkg/providers/ingress/translation/annotations/upstreamscheme/upstreamscheme.go
  pkg/providers/ingress/translation/annotations/upstreamscheme/upstreamscheme_test.go
  pkg/providers/ingress/translation/translator.go
  pkg/types/apisix/v1/types.go
  test/e2e/suite-annotations/upstreamprotocol.go
Labels: feature, area/controller

#1495 fix: use field cluster.name as value but not "default"
  pkg/apisix/consumer.go
  pkg/apisix/global_rule.go
  pkg/apisix/plugin.go
  pkg/apisix/plugin_metadata.go
  pkg/apisix/pluginconfig.go
  pkg/apisix/route.go
  pkg/apisix/schema.go
  pkg/apisix/ssl.go
  pkg/apisix/stream_route.go
  pkg/apisix/upstream.go
  pkg/apisix/upstreamservicerelation.go
Labels: area/controller

#1487 feat: support annotation of response-rewrite
  docs/en/latest/concepts/annotations.md
  pkg/providers/ingress/translation/annotations/plugins/plugins.go
  pkg/providers/ingress/translation/annotations/plugins/response_rewrite.go
  pkg/providers/ingress/translation/annotations/plugins/response_rewrite_test.go
  pkg/providers/ingress/translation/annotations/types.go
  test/e2e/suite-annotations/response_rewrite.go
Labels: area/controller

#1498 chore: use httptest.NewRequest instead of http.Request as incoming server request in test case
  pkg/api/router/router_test.go
Labels: CI

#1386 fix: many namespace lead to provider stuck
  pkg/providers/apisix/provider.go
  pkg/providers/apisix/provider_init.go
Labels: area/controller

#1486 feat: support secret plugin config
  docs/en/latest/concepts/apisix_route.md
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/translation/apisix_pluginconfig.go
  pkg/providers/apisix/translation/apisix_route.go
  samples/deploy/crd/v1/ApisixPluginConfig.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-plugins/suite-plugins-general/secret_ref.go
Labels: area/controller

#1504 ci: using ubuntu-20.04 by default
  .github/workflows/e2e-test-ci-v2-cron.yml
  .github/workflows/e2e-test-ci.yml
  .github/workflows/k8s-timer-ci.yml
Labels: CI

#1527 docs: add external service tutorial
  docs/en/latest/tutorials/external-service.md
Labels: documentation

#1530 refactor: unified factory and informer
  pkg/providers/apisix/apisix_cluster_config.go
  pkg/providers/apisix/apisix_consumer.go
  pkg/providers/apisix/apisix_plugin_config.go
  pkg/providers/apisix/apisix_route.go
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/apisix/provider.go
  pkg/providers/apisix/provider_init.go
  pkg/providers/controller.go
  pkg/providers/ingress/ingress.go
  pkg/providers/ingress/provider.go
  pkg/providers/k8s/configmap/configmap.go
  pkg/providers/k8s/configmap/provider.go
  pkg/providers/k8s/namespace/namespace_provider.go
  pkg/providers/k8s/pod/provider.go
  pkg/providers/types/types.go
Labels: area/controller

#1544 docs: update APISIX CRD tutorial
  docs/en/latest/tutorials/proxy-the-httpbin-service.md
Labels: documentation

#1549 chore: useless annotations warn logs
  pkg/providers/ingress/translation/annotations/upstreamscheme/upstreamscheme.go
Labels: area/controller

#1551 fix: Bad configuration item: apisix-admin-api-version
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: bug, area/controller, process/cherry-pick

#1543 docs: add match stream route with SNI tutorial
  docs/en/latest/tutorials/match-stream-route-by-sni.md
Labels: documentation

#1558 chore: admin-api default version v2
  pkg/config/config.go
Labels: area/controller, process/cherry-pick

#1526 feat: sync route crd labels to apisix
  pkg/providers/apisix/translation/apisix_route.go
  test/e2e/suite-chore/consistency.go
Labels: feature, area/controller, triage/accepted

#1490 chore: rename TranslateXXNotStrictly to GenerateXXDeleteMark
  pkg/providers/apisix/apisix_plugin_config.go
  pkg/providers/apisix/apisix_route.go
  pkg/providers/apisix/provider_init.go
  pkg/providers/apisix/translation/apisix_pluginconfig.go
  pkg/providers/apisix/translation/apisix_pluginconfig_test.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/apisix_route_test.go
  pkg/providers/apisix/translation/apisix_upstream.go
  pkg/providers/apisix/translation/translator.go
Labels: changelog, area/controller
