Repository apache/apisix-ingress-controller, pull requests merged in 2022-09, with the labels that each got.

#1303 [v1.5] fix: type assertion failed
  pkg/ingress/apisix_cluster_config.go
  pkg/ingress/apisix_consumer.go
  pkg/ingress/apisix_upstream.go
  pkg/ingress/endpointslice.go
Labels: bug, area/controller

#1314 fix: type assertion failed
  pkg/providers/apisix/apisix_consumer.go
Labels: bug, area/controller

#1311 fix: ingress class not effect in resource sync logic
  pkg/providers/ingress/ingress.go
Labels: area/controller

#1251 fix: support resolveGranularity of ApisixRoute
  pkg/apisix/apisix.go
  pkg/apisix/cache/memdb_test.go
  pkg/apisix/nonexistentclient.go
  pkg/apisix/resource_test.go
  pkg/apisix/upstream.go
  pkg/apisix/upstreamservicerelation.go
  pkg/apisix/upstreamservicerelation_test.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/apisix/translation/apisix_plugin_test.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/apisix_upstream.go
  pkg/providers/gateway/translation/gateway_httproute.go
  pkg/providers/gateway/translation/gateway_tlsroute.go
  pkg/providers/ingress/translation/translator.go
  pkg/providers/k8s/endpoint/base.go
  pkg/providers/k8s/endpoint/endpoint.go
  pkg/providers/k8s/endpoint/endpointslice.go
  pkg/types/apisix/v1/types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  pkg/types/service.go
  test/e2e/suite-chore/resolvegranularity.go
Labels: area/controller

#1329 feat: support update and delete of HTTPRoute (#1315)
  pkg/ingress/gateway/gateway_httproute.go
  test/e2e/scaffold/k8s.go
  test/e2e/suite-gateway/gateway_httproute.go
Labels: area/controller

#1330 fix: ingress class not effect in resource sync logic (#1311)
  pkg/ingress/ingress.go
Labels: bug, area/controller

#1334 docs: add powered-by.md
  powered-by.md
Labels: documentation

#1335 fix: crd resource status is not updated
  pkg/providers/utils/status.go
Labels: area/controller

#1331 fix: Using different protocols at the same time in ApisixUpstream
  pkg/providers/apisix/apisix_upstream.go
Labels: bug, area/controller

#1333 docs: add slack invitation badge
  README.md
Labels: documentation

#1336 [v1.5 cherry-pick]fix: crd resource status is not updated (#1335)
  pkg/ingress/status.go
Labels: area/controller

#1337 docs: update user cases
  powered-by.md
Labels: documentation

#1243 feat: update secret referenced by ingress
  go.mod
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/apisix/provider.go
  pkg/providers/apisix/translation/apisix_ssl.go
  pkg/providers/controller.go
  pkg/providers/gateway/gateway.go
  pkg/providers/ingress/ingress.go
  pkg/providers/ingress/provider.go
  pkg/providers/ingress/translation/annotations/types.go
  pkg/providers/ingress/translation/translator.go
  pkg/providers/k8s/provider.go
  pkg/providers/k8s/secret.go
  pkg/providers/translation/meta_const.go
  pkg/providers/translation/util.go
  pkg/providers/types/types.go
  pkg/providers/utils/ingress_status.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite-ingress/suite-ingress-features/secret.go
  test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go
  test/e2e/suite-ingress/suite-ingress-resource/ssl.go
Labels: area/controller

#1350 docs: modify powered-by.md
  powered-by.md
Labels: documentation

#1360 chore: release v1.5.0
  CHANGELOG.md
  Makefile
  docs/en/latest/FAQ.md
Labels: documentation

#1358 e2e: remove debug log
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/scaffold/scaffold.go
Labels: area/test

#1217 feat: support gateway/tcproute
  pkg/providers/gateway/gateway_tcproute.go
  pkg/providers/gateway/provider.go
  pkg/providers/gateway/translation/gateway.go
  pkg/providers/gateway/translation/gateway_httproute.go
  pkg/providers/gateway/translation/gateway_httproute_test.go
  pkg/providers/gateway/translation/gateway_tcproute.go
  pkg/providers/gateway/translation/gateway_tcproute_test.go
  pkg/providers/gateway/translation/gateway_tlsroute.go
  pkg/providers/gateway/translation/translator.go
  pkg/providers/utils/generic.go
  test/e2e/scaffold/ingress.go
  test/e2e/suite-gateway/gateway_tcproute.go
Labels: enhancement, area/controller
