Repository apache/apisix-ingress-controller, pull requests merged in 2022-05, with the labels that each got.

#996 chore: update apisix to 2.13.1
  Makefile
Labels: area/test

#1007 docs: fix link in certificate management docs (#998)
  docs/en/latest/practices/manage-certificates-with-cert-manager.md
  docs/en/latest/practices/manage-ingress-certificates-with-cert-manager.md
Labels: documentation

#972 Doc: add 'enable authentication and restriction' document
  docs/en/latest/practices/enable-authentication-and-restriction.md
Labels: documentation

#1012 feat: modify metrics name `apisix_bad_status_codes` to `apisix_status_codes`
  docs/assets/other/json/apisix-ingress-controller-grafana.json
  pkg/metrics/prometheus.go
  pkg/metrics/prometheus_test.go
Labels: changelog, area/controller

#975 feat: update an redirect annotation for ingress resource
  pkg/kube/translation/annotations/redirect.go
  pkg/types/apisix/v1/plugin_types.go
  test/e2e/suite-annotations/redirect.go
Labels: enhancement, changelog, area/controller

#985 feat:add authorization-annotation the ingress resource
  pkg/kube/translation/annotations.go
  pkg/kube/translation/annotations/authorization.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  test/e2e/scaffold/consumer.go
  test/e2e/suite-annotations/authorization.go
Labels: changelog, area/controller

#977 feat: support ApisixClusterConfig v2
  cmd/ingress/ingress.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ingress/apisix_cluster_config.go
  pkg/ingress/controller.go
  pkg/ingress/status.go
  pkg/kube/apisix_cluster_config.go
  pkg/kube/translation/global_rule.go
  pkg/kube/translation/global_rule_test.go
  pkg/kube/translation/translator.go
Labels: changelog, area/controller

#1009 feat: add jwt-auth authorization method
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v2beta3/types.go
  pkg/kube/apisix/apis/config/v2beta3/zz_generated.deepcopy.go
  pkg/kube/translation/apisix_consumer.go
  pkg/kube/translation/apisix_consumer_test.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/plugin.go
  pkg/kube/translation/plugin_test.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  samples/deploy/crd/v1/ApisixConsumer.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-features/consumer.go
Labels: area/controller

#1011 feat: add wolf-rbac authorization method.
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v2beta3/types.go
  pkg/kube/apisix/apis/config/v2beta3/zz_generated.deepcopy.go
  pkg/kube/translation/apisix_consumer.go
  pkg/kube/translation/apisix_consumer_test.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/plugin.go
  pkg/kube/translation/plugin_test.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  samples/deploy/crd/v1/ApisixConsumer.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/scaffold/wolf-rbac.go
  test/e2e/suite-features/consumer.go
  test/e2e/testdata/wolf-rbac/docker-compose.yaml
  test/e2e/testdata/wolf-rbac/ip.sh
  test/e2e/testdata/wolf-rbac/start.sh
  test/e2e/testdata/wolf-rbac/stop.sh
Labels: enhancement, area/controller

#1025 doc: add apisix_pluginconfig document
  docs/en/latest/config.json
  docs/en/latest/references/apisix_pluginconfig.md
Labels: documentation

#1028 doc: paraphrasing some descriptions about plugins
  docs/en/latest/references/apisix_pluginconfig.md
  docs/en/latest/references/apisix_route_v2beta3.md
Labels: documentation

#1023 feat: add csrf plugin annotation in ingress resource
  pkg/kube/translation/annotations.go
  pkg/kube/translation/annotations/csrf.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  test/e2e/suite-annotations/csrf.go
Labels: enhancement

#1016 e2e-test: add e2e tests and CRDs for ApisixClusterConfig v2
  samples/deploy/crd/v1/ApisixClusterConfig.yaml
  test/e2e/scaffold/cluster_config.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-features/global_rule.go
Labels: area/test

#1055 test: fix wolf-rbac and mTLS test cases
  docs/en/latest/deployments/ack.md
  docs/en/latest/practices/mtls/ca.pem
  docs/en/latest/practices/mtls/server.key
  docs/en/latest/practices/mtls/server.pem
  docs/en/latest/practices/mtls/user.key
  docs/en/latest/practices/mtls/user.pem
  test/e2e/suite-ingress/ssl.go
  test/e2e/testdata/wolf-rbac/docker-compose.yaml
Labels: area/test
