Repository apache/apisix-ingress-controller, pull requests merged in 2022-08, with the labels that each got.

#1211 docs: fix dead link
  docs/en/latest/FAQ.md
Labels: documentation

#1215 doc: Refactor the README
  README.md
Labels: documentation

#1219 chore: v1.5.0-rc1 release
  CHANGELOG.md
  Makefile
  releases/v1.5.0.toml
Labels: documentation

#1220 docs: add installation on KIND to index
  docs/en/latest/config.json
  install.md
Labels: documentation

#1203 ci: add cronjob runs e2e in multiple k8s versions
  .github/workflows/k8s-timer-ci.yml
  .gitignore
  Makefile
  test/e2e/scaffold/ingress.go
  test/e2e/suite-features/retries.go
  utils/kind-with-registry.sh
Labels: area/test

#1239 chore: update contributor over time link for README
  README.md
Labels: documentation

#1200 feat: add log rotate
  CHANGELOG.md
  cmd/ingress/ingress.go
  cmd/ingress/ingress_test.go
  conf/config-default.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
Labels: enhancement, area/controller

#1241 docs: Fix typo on plugin config name
  docs/en/latest/concepts/annotations.md
Labels: documentation

#1244 chore(deps): bump go.uber.org/zap and github.com/prometheus/client_golang
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1246 fix: TestRotateLog
  cmd/ingress/ingress_test.go
Labels: area/test

#1222 fix: nodes convert failed
  pkg/apisix/resource_test.go
  pkg/types/apisix/v1/types.go
Labels: area/controller, process/cherry-pick

#1216 fix: log Secret name instead of all data
  pkg/providers/k8s/secret.go
Labels: area/controller

#1250 [v1.5.0 cherry-pick] fix: nodes convert failed (#1222)
  pkg/apisix/resource_test.go
  pkg/types/apisix/v1/types.go
Labels: area/controller

#1247 docs: update "Getting started" guide
  docs/en/latest/config.json
  docs/en/latest/deployments/ack.md
  docs/en/latest/getting-started.md
Labels: documentation

#1056 feat: add mqtt-proxy plugin in ApisixRoute (#966)
  .github/workflows/spell-checker.yml
  docs/en/latest/references/apisix_route_v2.md
  pkg/api/validation/apisix_route_test.go
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/types/apisix/v1/types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-plugins/suite-plugins-other/mqtt-proxy.go
Labels: enhancement, area/controller

#1265 chore(deps): bump deps from 0.24.3 to 0.24.4
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1268 fix: object type should be apisix_upstream and endpointslice and apisix_cluster_config
  pkg/providers/apisix/apisix_cluster_config.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/k8s/endpoint/endpointslice.go
Labels: bug, area/controller, process/cherry-pick

#1274 ci: set default_branch
  .github/workflows/k8s-timer-ci.yml
Labels: area/test

#1272 docs: update installation guide
  docs/en/latest/config.json
  docs/en/latest/deployments/aws.md
  docs/en/latest/deployments/azure.md
  docs/en/latest/deployments/gke.md
  docs/en/latest/deployments/k3s-rke.md
  docs/en/latest/deployments/kind.md
  docs/en/latest/deployments/kubesphere.md
  docs/en/latest/deployments/minikube.md
  docs/en/latest/deployments/tke.md
Labels: documentation

#1238 fix: namespace_selector invalid when restarting
  pkg/api/validation/utils.go
  pkg/api/validation/utils_test.go
  pkg/providers/k8s/namespace/namespace_provider.go
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/k8s.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/suite-ingress-features/namespace.go
Labels: bug, area/controller, process/cherry-pick

#1279 docs:add ApisixUpstream healthCheck explanation to resolveGranularity
  docs/en/latest/references/apisix_route_v2.md
  docs/en/latest/references/apisix_route_v2beta3.md
Labels: documentation

#1297 e2e: delete duplicate log data on e2e-test failure
  test/e2e/scaffold/scaffold.go
Labels: area/test

#1293 docs: add powered-by.md
  README.md
  powered-by.md
Labels: documentation

#1245 refactor: annotations
  pkg/providers/ingress/translation/annotations.go
  pkg/providers/ingress/translation/annotations/pluginconfig/pluginconfig.go
  pkg/providers/ingress/translation/annotations/plugins/authorization.go
  pkg/providers/ingress/translation/annotations/plugins/cors.go
  pkg/providers/ingress/translation/annotations/plugins/cors_test.go
  pkg/providers/ingress/translation/annotations/plugins/csrf.go
  pkg/providers/ingress/translation/annotations/plugins/forward_auth.go
  pkg/providers/ingress/translation/annotations/plugins/forward_auth_test.go
  pkg/providers/ingress/translation/annotations/plugins/iprestriction.go
  pkg/providers/ingress/translation/annotations/plugins/iprestriction_test.go
  pkg/providers/ingress/translation/annotations/plugins/plugins.go
  pkg/providers/ingress/translation/annotations/plugins/redirect.go
  pkg/providers/ingress/translation/annotations/plugins/rewrite.go
  pkg/providers/ingress/translation/annotations/regex/regex.go
  pkg/providers/ingress/translation/annotations/types.go
  pkg/providers/ingress/translation/annotations/websocket/websocket.go
  pkg/providers/ingress/translation/annotations_test.go
  pkg/providers/ingress/translation/translator.go
Labels: area/controller
