Repository apache/apisix-ingress-controller, pull requests merged in 2022-10, with the labels that each got.

#1373 chore: release v1.5.0 (#1360)
  CHANGELOG.md
  Makefile
Labels: documentation

#1278 feat: add Gateway UDPRoute
  pkg/providers/gateway/gateway_udproute.go
  pkg/providers/gateway/provider.go
  pkg/providers/gateway/translation/gateway.go
  pkg/providers/gateway/translation/gateway_udproute.go
  pkg/providers/gateway/translation/translator.go
  pkg/types/apisix/v1/types.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/test_backend.go
  test/e2e/suite-gateway/gateway_udproute.go
Labels: area/controller

#1306 feat: support external service
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/kube/apisix_upstream.go
  pkg/providers/apisix/apisix_route.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/apisix/provider.go
  pkg/providers/apisix/translation/apisix_plugin.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/apisix_route_test.go
  pkg/providers/apisix/translation/apisix_upstream.go
  pkg/providers/apisix/translation/translator.go
  pkg/providers/utils/string.go
  pkg/types/apisix/v1/types.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  samples/deploy/crd/v1/ApisixUpstream.yaml
  test/e2e/go.mod
  test/e2e/scaffold/k8s.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-features/external-service.go
Labels: changelog, area/controller

#1391 docs: update ApisixRoute docs
  docs/en/latest/concepts/apisix_route.md
Labels: documentation

#1396 docs: ensure parity in examples
  docs/en/latest/getting-started.md
Labels: documentation

#1398 docs: fix typo
  docs/en/latest/getting-started.md
Labels: documentation

#1392 feat: ingress extensions/v1beta1 support tls
  pkg/providers/ingress/translation/translator.go
  test/e2e/suite-ingress/suite-ingress-resource/ingress.go
Labels: feature

#1397 chore(deps): bump k8s.io/client-go from 0.25.2 to 0.25.3
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1399 docs: update annotations page
  docs/en/latest/concepts/annotations.md
Labels: documentation

#1407 docs: update ApisixUpstream docs
  .github/workflows/e2e-test-ci.yml
  docs/en/latest/concepts/apisix_upstream.md
Labels: documentation

#1409 fix: handle v2 ApisixPluginConfig status
  pkg/ingress/status.go
Labels: bug

#1414 docs: update "ApisixTls" and "ApisixClusterConfig"
  docs/en/latest/concepts/apisix_cluster_config.md
  docs/en/latest/concepts/apisix_tls.md
Labels: documentation

#1369 feat: support plugin_metadata of apisix
  cmd/ingress/ingress.go
  conf/config-default.yaml
  conf/plugin-metadata-config-map.yaml
  pkg/apisix/apisix.go
  pkg/apisix/cluster.go
  pkg/apisix/consumer.go
  pkg/apisix/global_rule.go
  pkg/apisix/nonexistentclient.go
  pkg/apisix/plugin_metadata.go
  pkg/apisix/pluginconfig.go
  pkg/apisix/resource.go
  pkg/apisix/route.go
  pkg/apisix/ssl.go
  pkg/apisix/stream_route.go
  pkg/apisix/upstream.go
  pkg/config/config.go
  pkg/providers/controller.go
  pkg/providers/k8s/configmap/configmap.go
  pkg/providers/k8s/configmap/provider.go
  pkg/providers/k8s/configmap/translation/configyaml__parser_test.go
  pkg/providers/k8s/configmap/translation/configyaml_parser.go
  pkg/providers/k8s/configmap/translation/parse.go
  pkg/providers/k8s/configmap/translation/translation.go
  pkg/providers/k8s/provider.go
  pkg/providers/types/types.go
  pkg/providers/utils/manifest.go
  pkg/types/apisix/v1/types.go
  test/e2e/go.mod
  test/e2e/scaffold/k8s.go
  test/e2e/suite-chore/admin_api.go
  test/e2e/suite-ingress/suite-ingress-resource/configmap.go
  test/e2e/suite-ingress/suite-ingress-resource/stream.go
Labels: feature
