Repository apache/apisix-ingress-controller, pull requests merged in 2022-07, with the labels that each got.

#1101 feat: ingress annotations support enable websocket
  docs/en/latest/concepts/annotations.md
  pkg/kube/translation/ingress.go
  pkg/kube/translation/ingress_test.go
  test/e2e/suite-annotations/websocket.go
Labels: enhancement, area/controller

#1137 doc: fix enable-authentication-and-restriction.md link failed
  docs/en/latest/tutorials/enable-authentication-and-restriction.md
Labels: documentation

#1135 fix: verify through the cache first, then delete
  pkg/apisix/pluginconfig.go
  pkg/apisix/upstream.go
Labels: area/controller

#1133 chore: make api version const consistent
  cmd/ingress/ingress.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ingress/apisix_route.go
  pkg/ingress/compare.go
  pkg/ingress/controller.go
  pkg/kube/apisix_route.go
  test/e2e/scaffold/k8s.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-chaos/chaos.go
  test/e2e/suite-config/config.go
  test/e2e/suite-ingress/suite-ingress-features/resourcesync.go
Labels: area/controller

#1132 chore: add log for syncManifest delete upstream
  pkg/ingress/apisix_route.go
  pkg/ingress/utils/manifest.go
  pkg/log/default_logger.go
  pkg/log/logger.go
Labels: area/controller

#1143 ci: pin skywalking-eyes to v0.3.0 release
  .github/workflows/license-checker.yml
Labels: CI

#1140 feat: support endpointslice, and improve test/e2e/endpoints.go tests.
  pkg/ingress/endpoint.go
  pkg/ingress/endpointslice.go
  test/e2e/scaffold/k8s.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-endpoints/endpoints.go
Labels: area/controller

#1141 chore: ApisixUpstream v2
  cmd/ingress/ingress.go
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ingress/apisix_upstream.go
  pkg/ingress/controller.go
  pkg/ingress/gateway/translation/gateway_httproute_test.go
  pkg/ingress/status.go
  pkg/kube/apisix_upstream.go
  pkg/kube/translation/apisix_route_test.go
  pkg/kube/translation/apisix_upstream.go
  pkg/kube/translation/apisix_upstream_test.go
  pkg/kube/translation/ingress_test.go
  pkg/kube/translation/plugin_test.go
  pkg/kube/translation/translator.go
  pkg/kube/translation/translator_test.go
  test/e2e/suite-chaos/chaos.go
  test/e2e/suite-config/config.go
Labels: area/controller

#1134 docs: update crd version
  docs/en/latest/concepts/apisix_cluster_config.md
  docs/en/latest/concepts/apisix_route.md
  docs/en/latest/concepts/apisix_tls.md
  docs/en/latest/concepts/apisix_upstream.md
  docs/en/latest/tutorials/mtls/mtls.yaml
  docs/en/latest/tutorials/mtls/tls.yaml
  docs/en/latest/tutorials/proxy-grpc-service.md
  docs/en/latest/tutorials/proxy-the-httpbin-service.md
  docs/en/latest/upgrade.md
Labels: documentation

#1160 chore(deps): some dependency updates
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1149 ci: upgrade e2e-test-ci
  .github/actions/e2e/action.yaml
  .github/workflows/e2e-test-ci.yml
  Makefile
  pkg/kube/translation/apisix_route_test.go
  test/e2e/README.md
  test/e2e/e2e.go
  test/e2e/scaffold/etcd.go
  test/e2e/scaffold/httpbin.go
  test/e2e/scaffold/ingress.go
  test/e2e/suite-annotations/websocket.go
  test/e2e/suite-chore/chaos.go
  test/e2e/suite-chore/config.go
  test/e2e/suite-chore/endpoints.go
  test/e2e/suite-config/manifests.go
  test/e2e/suite-features/websocket.go
  test/e2e/suite-ingress/suite-ingress-features/resourcesync.go
  test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go
  test/e2e/suite-plugins/suite-plugins-general/echo.go
  test/e2e/suite-plugins/suite-plugins-general/redirect.go
  test/e2e/suite-plugins/suite-plugins-other/plugin_config.go
  test/e2e/suite-plugins/suite-plugins-security/cors.go
  test/e2e/suite-plugins/suite-plugins-security/ip-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/uri_blocker.go
  test/e2e/suite-plugins/suite-plugins-traffic/limit_count.go
  test/e2e/suite-plugins/suite-plugins-traffic/request_id.go
  test/e2e/suite-plugins/suite-plugins-transformation/fault_injection.go
  utils/kind-with-registry.sh
Labels: area/test

#1158 test: keep namespace when test failed in dev mod
  .github/workflows/e2e-test-ci.yml
  Makefile
  test/e2e/README.md
  test/e2e/scaffold/scaffold.go
Labels: area/test

#1145 chore: update APISIX v2.14.1
  Makefile
  test/e2e/suite-annotations/redirect.go
  test/e2e/suite-ingress/suite-ingress-resource/ssl.go
  test/e2e/suite-plugins/suite-plugins-authentication/hmac.go
  test/e2e/suite-plugins/suite-plugins-general/redirect.go
Labels: area/test

#1188 fix: ScopeQuery should be case sensitive (#1168)
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/apisix_route_test.go
  test/e2e/suite-features/route_match_exprs.go
Labels: bug, area/controller

#1189 docs: update all api-version to v2
  docs/en/latest/concepts/annotations.md
  docs/en/latest/concepts/apisix_cluster_config.md
  docs/en/latest/concepts/apisix_route.md
  docs/en/latest/concepts/apisix_tls.md
  docs/en/latest/concepts/apisix_upstream.md
  docs/en/latest/design.md
  docs/en/latest/plugins/prometheus.md
  docs/en/latest/tutorials/check-crd-status.md
  docs/en/latest/tutorials/enable-authentication-and-restriction.md
  docs/en/latest/tutorials/how-to-access-Apache-APISIX-Prometheus-Metrics-on-k8s.md
  docs/en/latest/tutorials/how-to-use-go-plugin-runner-in-apisix-ingress.md
  docs/en/latest/tutorials/manage-certificates-with-cert-manager.md
  docs/en/latest/tutorials/mtls.md
  docs/en/latest/tutorials/mtls/mtls.yaml
  docs/en/latest/tutorials/mtls/route.yaml
  docs/en/latest/tutorials/mtls/tls.yaml
  docs/en/latest/tutorials/proxy-grpc-service.md
  docs/en/latest/tutorials/proxy-the-httpbin-service.md
  docs/en/latest/tutorials/the-hard-way.md
  docs/en/latest/upgrade.md
Labels: documentation

#1191 fix: translate error of old ApisixRoute
  pkg/ingress/apisix_route.go
  pkg/ingress/utils/manifest.go
  test/e2e/suite-chore/consistency.go
Labels: bug, area/controller

#1131 deploy: update deploy cluster role
  samples/deploy/rbac/apisix_view_clusterrole.yaml
Labels: area/helm

#1192 fix: apisix_upstream sync panic
  pkg/ingress/apisix_upstream.go
Labels: area/controller

#1195 doc: add a notice about the compatibility of Ingress and Dashboard
  README.md
Labels: documentation

#1193 fix: translate error of old Ingress
  pkg/ingress/apisix_route.go
  pkg/ingress/controller.go
  pkg/ingress/ingress.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/ingress.go
  pkg/kube/translation/translator.go
  test/e2e/suite-chore/consistency.go
Labels: area/controller

#1196 e2e: add sync test case
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/suite-ingress-features/resourcesync.go
Labels: area/test

#1197 chore: Using APISIX 2.15.0 for CI
  Makefile
Labels: area/test

#1198 chore: mark v2beta3 deprecated
  cmd/ingress/ingress.go
  cmd/ingress/testdata/conf.json
  cmd/ingress/testdata/config
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-annotations/authorization.go
  test/e2e/suite-chore/endpoints.go
  test/e2e/suite-features/global_rule.go
  test/e2e/suite-features/healthcheck.go
  test/e2e/suite-features/remote_addrs_match.go
  test/e2e/suite-features/retries.go
  test/e2e/suite-features/route_match_exprs.go
  test/e2e/suite-features/scheme.go
  test/e2e/suite-features/subset.go
  test/e2e/suite-features/traffic_split.go
  test/e2e/suite-features/websocket.go
  test/e2e/suite-ingress/suite-ingress-features/compare.go
  test/e2e/suite-ingress/suite-ingress-features/sanity.go
  test/e2e/suite-ingress/suite-ingress-features/secret.go
  test/e2e/suite-ingress/suite-ingress-features/status.go
  test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go
  test/e2e/suite-ingress/suite-ingress-resource/ssl.go
  test/e2e/suite-ingress/suite-ingress-resource/stream.go
  test/e2e/suite-ingress/suite-ingress-resource/upstream_tls.go
  test/e2e/suite-plugins/suite-plugins-authentication/basic.go
  test/e2e/suite-plugins/suite-plugins-authentication/hmac.go
  test/e2e/suite-plugins/suite-plugins-authentication/jwt.go
  test/e2e/suite-plugins/suite-plugins-authentication/key.go
  test/e2e/suite-plugins/suite-plugins-authentication/wolfrbac.go
  test/e2e/suite-plugins/suite-plugins-general/echo.go
  test/e2e/suite-plugins/suite-plugins-general/redirect.go
  test/e2e/suite-plugins/suite-plugins-other/plugin_config.go
  test/e2e/suite-plugins/suite-plugins-other/serverless.go
  test/e2e/suite-plugins/suite-plugins-security/consumer-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/cors.go
  test/e2e/suite-plugins/suite-plugins-security/csrf.go
  test/e2e/suite-plugins/suite-plugins-security/ip-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/referer-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/uri_blocker.go
  test/e2e/suite-plugins/suite-plugins-traffic/api_breaker.go
  test/e2e/suite-plugins/suite-plugins-traffic/client-control.go
  test/e2e/suite-plugins/suite-plugins-traffic/limit_count.go
  test/e2e/suite-plugins/suite-plugins-traffic/request-validation.go
  test/e2e/suite-plugins/suite-plugins-traffic/request_id.go
  test/e2e/suite-plugins/suite-plugins-transformation/fault_injection.go
  test/e2e/suite-plugins/suite-plugins-transformation/proxy_rewrite.go
  test/e2e/suite-plugins/suite-plugins-transformation/response_rewrite.go
Labels: area/controller, area/test
