Repository apache/apisix-ingress-controller, pull requests merged in 2022-01, with the labels that each got.

#828 fix: consumer name contain "-"
  pkg/types/apisix/v1/types.go
Labels: area/controller

#830 bug: fix typo in ApidixRoute CRD
  samples/deploy/crd/v1/ApisixRoute.yaml
Labels: area/helm

#826 refactor: remove BaseURL and AdminKey in config
  cmd/ingress/ingress.go
  cmd/ingress/ingress_test.go
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: changelog, area/controller, do-not-merge/hold

#832 chore: update ingress/comapre.go watchingNamespac v2beta1 to v2beta3
  pkg/ingress/compare.go
Labels: area/controller

#827 feat: ensure that the lease can be actively released before program shutdown to reduce the time required for failover
  cmd/ingress/ingress.go
  pkg/ingress/controller.go
  test/e2e/ingress/sanity.go
Labels: area/controller
