Repository apache/apisix-ingress-controller, pull requests merged in 2022-04, with the labels that each got.

#946 docs: update the hard way.
  docs/en/latest/practices/the-hard-way.md
Labels: documentation, triage/accepted

#947 fix: ingress update event handler not filter by watching namespaces
  pkg/ingress/ingress.go
Labels: CI

#942 feat(e2e): add e2e test for prometheus
  Makefile
  test/e2e/features/global_rule.go
  test/e2e/plugins/server-info.go
Labels: area/test

#961 docs: fix subset field typo
  docs/en/latest/references/apisix_route_v2beta3.md
  test/e2e/README.md
Labels: documentation

#937 feat: support forward-auth plugin
  pkg/kube/translation/annotations.go
  pkg/kube/translation/annotations/forward_auth.go
  pkg/kube/translation/annotations/forward_auth_test.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  test/e2e/scaffold/k8s.go
  test/e2e/suite-annotations/forward_auth.go
Labels: enhancement, area/controller

#964 feat: add e2e test for serverless plugin
  test/e2e/suite-plugins/serverless.go
Labels: area/test

#965 ci: add 3 plugin test cases for e2e
  test/e2e/scaffold/consumer.go
  test/e2e/suite-plugins/client-control.go
  test/e2e/suite-plugins/consumer-restriction.go
  test/e2e/suite-plugins/csrf.go
Labels: area/test
