Repository apache/apisix-ingress-controller, pull requests merged in 2022-06, with the labels that each got.

#1044 e2e-test: add e2e tests and CRDs for ApisixConsumer v2
  samples/deploy/crd/v1/ApisixConsumer.yaml
  test/e2e/scaffold/consumer.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-annotations/authorization.go
  test/e2e/suite-features/consumer.go
Labels: area/test

#984 feat: support ApisixPluginConfig v2
  cmd/ingress/ingress.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ingress/apisix_pluginconfig.go
  pkg/ingress/controller.go
  pkg/kube/apisix_plugin_config.go
  pkg/kube/translation/apisix_pluginconfig.go
  pkg/kube/translation/translator.go
Labels: changelog, area/controller

#994 docs: add "how to use go plugin runner with APISIX Ingress"
  docs/en/latest/practices/how-to-use-go-plugin-runner-in-apisix-ingress.md
Labels: documentation

#1018 doc: update "enable-authentication-and-restriction.md" doc, and examples of `jwt-auth` and `wolf-rbac`.
  docs/en/latest/practices/enable-authentication-and-restriction.md
Labels: documentation

#1067 e2e-test: add e2e tests for ApisixPluginConfig v2
  samples/deploy/crd/v1/ApisixPluginConfig.yaml
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-plugins/plugin_config.go
Labels: area/test

#1031 doc(APISIX-Ingress): add how to change Admin API key of Apache APISIX…
  docs/en/latest/FAQ.md
Labels: documentation

#1073 docs: correct typo & link
  docs/en/latest/concepts/annotations.md
  docs/en/latest/concepts/apisix_route.md
  docs/en/latest/design.md
  docs/en/latest/practices/mtls.md
  docs/en/latest/practices/the-hard-way.md
Labels: documentation

#1080 fix: fix tag for keyAuth field
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2beta2/types.go
  pkg/kube/apisix/apis/config/v2beta3/types.go
Labels: area/controller

#1079 feat: support GatewayClass, refactor gateway modules
  pkg/ingress/apisix_pluginconfig.go
  pkg/ingress/apisix_route.go
  pkg/ingress/compare.go
  pkg/ingress/controller.go
  pkg/ingress/gateway/gateway.go
  pkg/ingress/gateway/gateway_class.go
  pkg/ingress/gateway/gateway_httproute.go
  pkg/ingress/gateway/provider.go
  pkg/ingress/gateway/translation/gateway_httproute.go
  pkg/ingress/gateway/translation/gateway_httproute_test.go
  pkg/ingress/gateway/translation/translator.go
  pkg/ingress/ingress.go
  pkg/ingress/namespace/namespace.go
  pkg/ingress/namespace/provider.go
  pkg/ingress/namespace/provider_mock.go
  pkg/ingress/pod_test.go
  pkg/ingress/status.go
  pkg/ingress/utils/executor.go
  pkg/ingress/utils/ingress_status.go
  pkg/ingress/utils/manifest.go
  pkg/ingress/utils/manifest_test.go
  pkg/ingress/utils/string.go
  pkg/kube/translation/apisix_pluginconfig.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/context.go
  pkg/kube/translation/context_test.go
  pkg/kube/translation/ingress.go
  pkg/kube/translation/plugin.go
  pkg/kube/translation/translator.go
  pkg/kube/translation/util.go
Labels: area/controller

#1078 fix: e2e robustness.
  Makefile
  test/e2e/scaffold/wolf-rbac.go
  test/e2e/suite-features/consumer.go
  test/e2e/suite-ingress/namespace.go
  test/e2e/testdata/wolf-rbac/cmd.sh
  test/e2e/testdata/wolf-rbac/ip.sh
  test/e2e/testdata/wolf-rbac/start.sh
  test/e2e/testdata/wolf-rbac/stop.sh
Labels: area/test

#1068 doc: add v2 ApisixRoute reference
  docs/en/latest/config.json
  docs/en/latest/references/apisix_cluster_config_v2.md
  docs/en/latest/references/apisix_cluster_config_v2beta3.md
  docs/en/latest/references/apisix_pluginconfig_v2.md
  docs/en/latest/references/apisix_pluginconfig_v2beta3.md
  docs/en/latest/references/apisix_route_v2.md
  docs/en/latest/references/apisix_tls_v2.md
  docs/en/latest/references/apisix_tls_v2beta3.md
Labels: documentation

#1093 feat: support v2 in resource compare
  pkg/ingress/compare.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/compare.go
Labels: area/controller

#1107 chore: enable stale GitHub action
  .github/workflows/stale.yml
Labels: triage/accepted

#1102 feat: sync CRD and ingress resource to apisix mechanism.
  cmd/ingress/ingress.go
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ingress/apisix_cluster_config.go
  pkg/ingress/apisix_consumer.go
  pkg/ingress/apisix_pluginconfig.go
  pkg/ingress/apisix_route.go
  pkg/ingress/apisix_tls.go
  pkg/ingress/apisix_upstream.go
  pkg/ingress/controller.go
  pkg/ingress/ingress.go
  samples/deploy/configmap/apisix-ingress-cm.yaml
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/k8s.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/resourcesync.go
Labels: area/controller

#1040 fix : The ingress backend is modified several times, resulting in residual update events
  pkg/ingress/ingress.go
  pkg/kube/translation/ingress.go
  pkg/kube/translation/ingress_test.go
  pkg/kube/translation/translator.go
Labels: area/controller

#1123 docs: rename practices to tutorials and add index
  docs/en/latest/config.json
  docs/en/latest/deployments/ack.md
  docs/en/latest/deployments/aws.md
  docs/en/latest/deployments/azure.md
  docs/en/latest/deployments/gke.md
  docs/en/latest/deployments/k3s-rke.md
  docs/en/latest/deployments/kind.md
  docs/en/latest/deployments/kubesphere.md
  docs/en/latest/deployments/minikube.md
  docs/en/latest/deployments/tke.md
  docs/en/latest/tutorials/cert-manager/ca.yaml
  docs/en/latest/tutorials/cert-manager/issuer.yaml
  docs/en/latest/tutorials/check-crd-status.md
  docs/en/latest/tutorials/enable-authentication-and-restriction.md
  docs/en/latest/tutorials/how-to-access-Apache-APISIX-Prometheus-Metrics-on-k8s.md
  docs/en/latest/tutorials/how-to-use-go-plugin-runner-in-apisix-ingress.md
  docs/en/latest/tutorials/index.md
  docs/en/latest/tutorials/manage-certificates-with-cert-manager.md
  docs/en/latest/tutorials/manage-ingress-certificates-with-cert-manager.md
  docs/en/latest/tutorials/mtls.md
  docs/en/latest/tutorials/mtls/ca.pem
  docs/en/latest/tutorials/mtls/client-ca-secret.yaml
  docs/en/latest/tutorials/mtls/mtls.yaml
  docs/en/latest/tutorials/mtls/route.yaml
  docs/en/latest/tutorials/mtls/server-secret.yaml
  docs/en/latest/tutorials/mtls/server.key
  docs/en/latest/tutorials/mtls/server.pem
  docs/en/latest/tutorials/mtls/tls.yaml
  docs/en/latest/tutorials/mtls/user.key
  docs/en/latest/tutorials/mtls/user.pem
  docs/en/latest/tutorials/proxy-grpc-service.md
  docs/en/latest/tutorials/proxy-the-httpbin-service-with-ingress.md
  docs/en/latest/tutorials/proxy-the-httpbin-service.md
  docs/en/latest/tutorials/the-hard-way.md
  install.md
Labels: documentation
