Repository apache/apisix-ingress-controller, pull requests merged in 2022-11, with the labels that each got.

#1377 feat: support k8s native ingress and backend service in different…
  pkg/providers/ingress/translation/annotations.go
  pkg/providers/ingress/translation/annotations/servicenamespace/servicenamespace.go
  pkg/providers/ingress/translation/annotations/types.go
  pkg/providers/ingress/translation/annotations_test.go
  pkg/providers/ingress/translation/translator.go
  test/e2e/suite-annotations/svc_namespace.go
Labels: feature, triage/accepted

#1431 chore: remove v2beta2 API Version
  pkg/api/validation/apisix_consumer.go
  pkg/api/validation/apisix_route.go
  pkg/api/validation/apisix_route_test.go
  pkg/api/validation/apisix_tls.go
  pkg/api/validation/apisix_upstream.go
  pkg/config/config.go
  pkg/kube/apisix/apis/config/v2beta2/doc.go
  pkg/kube/apisix/apis/config/v2beta2/types.go
  pkg/kube/apisix/apis/config/v2beta2/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v2beta2/zz_generated.register.go
  pkg/kube/apisix/client/clientset/versioned/clientset.go
  pkg/kube/apisix/client/clientset/versioned/fake/clientset_generated.go
  pkg/kube/apisix/client/clientset/versioned/fake/register.go
  pkg/kube/apisix/client/clientset/versioned/scheme/register.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/config_client.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/doc.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/fake/doc.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/fake/fake_apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/fake/fake_config_client.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta2/generated_expansion.go
  pkg/kube/apisix/client/informers/externalversions/config/interface.go
  pkg/kube/apisix/client/informers/externalversions/config/v2beta2/apisixroute.go
  pkg/kube/apisix/client/informers/externalversions/config/v2beta2/interface.go
  pkg/kube/apisix/client/informers/externalversions/generic.go
  pkg/kube/apisix/client/listers/config/v2beta2/apisixroute.go
  pkg/kube/apisix/client/listers/config/v2beta2/expansion_generated.go
  pkg/kube/apisix_route.go
  pkg/providers/apisix/apisix_route.go
  pkg/providers/apisix/provider.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/translator.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-chore/chaos.go
  test/e2e/suite-features/scheme.go
  utils/update-codegen.sh
  utils/verify-codegen.sh
Labels: changelog

#1429 feat: delete "app_namespace" param
  cmd/ingress/ingress.go
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: changelog, triage/accepted

#1051 feat: support sni based tls route
  pkg/apisix/stream_route.go
  pkg/apisix/stream_route_test.go
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/utils/manifest_test.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-ingress/suite-ingress-resource/stream.go
Labels: enhancement, area/controller

#1439 fix: #1412
  pkg/providers/apisix/translation/apisix_route.go
Labels: bug

#1446 modify Dockerfile go version from 1.18 to 1.19 ,consist with go mod
  Dockerfile
Labels: CI

#1437 docs: update "FAQ" page
  .github/workflows/lint-checker.yml
  docs/en/latest/FAQ.md
  docs/en/latest/references/apisix_upstream.md
Labels: documentation

#1443 docs: update "Development" guide
  docs/en/latest/contribute.md
Labels: documentation

#1445 chore: gateway-api v0.5.1
  Makefile
  go.mod
  go.sum
  pkg/kube/init.go
  pkg/providers/gateway/gateway.go
  pkg/providers/gateway/gateway_class.go
  pkg/providers/gateway/gateway_httproute.go
  pkg/providers/gateway/provider.go
  pkg/providers/gateway/translation/gateway.go
  pkg/providers/gateway/translation/gateway_httproute.go
  pkg/providers/gateway/translation/gateway_httproute_test.go
  pkg/providers/gateway/translation/translator.go
  pkg/providers/gateway/types/types.go
  samples/deploy/gateway-api/gateway.networking.k8s.io_gatewayclasses.yaml
  samples/deploy/gateway-api/gateway.networking.k8s.io_gateways.yaml
  samples/deploy/gateway-api/gateway.networking.k8s.io_httproutes.yaml
  samples/deploy/gateway-api/gateway.networking.k8s.io_referencepolicies.yaml
  samples/deploy/gateway-api/gateway.networking.k8s.io_tcproutes.yaml
  samples/deploy/gateway-api/gateway.networking.k8s.io_tlsroutes.yaml
  samples/deploy/gateway-api/gateway.networking.k8s.io_udproutes.yaml
  samples/deploy/gateway-api/v0.5.1/experimental-install.yaml
  samples/deploy/gateway-api/v0.5.1/standard-install.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/controller

#1464 cherry-pick #1331: fix: Using different protocols at the same time in…
  pkg/ingress/apisix_upstream.go
Labels: bug

#1459 docs: update API references
  docs/en/latest/references/apisix_cluster_config_v2.md
  docs/en/latest/references/apisix_cluster_config_v2beta3.md
  docs/en/latest/references/apisix_pluginconfig_v2.md
  docs/en/latest/references/apisix_pluginconfig_v2beta3.md
  docs/en/latest/references/apisix_tls_v2.md
  docs/en/latest/references/apisix_tls_v2beta3.md
Labels: documentation

#1450 docs: update ApisixUpstream reference
  docs/en/latest/references/apisix_upstream.md
Labels: documentation

#1417 Feat (dev env): allow to custom registry port for `make kind-up`
  Makefile
  utils/kind-with-registry.sh
Labels: area/test

#1467 docs: Add more descriptions and examples in the prometheus doc
  docs/en/latest/tutorials/how-to-access-Apache-APISIX-Prometheus-Metrics-on-k8s.md
Labels: documentation

#1449 feat: support apisix v3 admin api
  .github/workflows/e2e-test-ci-v2-cron.yml
  Makefile
  cmd/ingress/ingress.go
  conf/config-default.yaml
  pkg/api/server.go
  pkg/api/validation/utils.go
  pkg/apisix/apisix.go
  pkg/apisix/cluster.go
  pkg/apisix/cluster_test.go
  pkg/apisix/consumer.go
  pkg/apisix/global_rule.go
  pkg/apisix/plugin_metadata.go
  pkg/apisix/pluginconfig.go
  pkg/apisix/resource.go
  pkg/apisix/route.go
  pkg/apisix/ssl.go
  pkg/apisix/stream_route.go
  pkg/apisix/upstream.go
  pkg/config/config.go
  pkg/kube/apisix_cluster_config.go
  pkg/providers/apisix/apisix_cluster_config.go
  pkg/providers/controller.go
  test/e2e/README.md
  test/e2e/scaffold/apisix.go
  test/e2e/scaffold/cluster_config.go
  test/e2e/scaffold/etcd.go
  test/e2e/scaffold/httpbin.go
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/k8s.go
  test/e2e/scaffold/scaffold.go
  test/e2e/scaffold/ssl.go
  test/e2e/scaffold/test_backend.go
  test/e2e/scaffold/upstream_tls.go
  test/e2e/testdata/apisix-gw-config-v3.yaml
Labels: area/test/apiv2

#1466 feat: support variable in ApisixRoute exprs scope
  pkg/kube/apisix/const/const.go
  pkg/providers/apisix/translation/apisix_route.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-features/route_match_exprs.go
Labels: area/controller

#1469 fix: cluster.metricsCollector invoked before assign when MountWebhooks(#1428)
  pkg/api/server.go
Labels: bug

#1474 chore: v1.5.1 release
  CHANGELOG.md
  Makefile
  docs/en/latest/references/apisix_upstream.md
  releases/v1.5.1.toml
Labels: area/controller

#1465 feat: add support for integrate with DP service discovery
  pkg/apisix/cluster.go
  pkg/apisix/upstreamservicerelation.go
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/apisix_upstream.go
  pkg/providers/k8s/endpoint/endpointslice.go
  pkg/providers/translation/apisix_upstream.go
  pkg/providers/types/types.go
  pkg/types/apisix/v1/types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  samples/deploy/crd/v1/ApisixUpstream.yaml
  test/e2e/suite-features/external-sd.go
  test/e2e/testdata/apisix-gw-config-v3-with-sd.yaml
  test/e2e/testdata/apisix-gw-config-with-sd.yaml
Labels: area/controller

#1425 docs: ingress class annotation to spec (#1421)
  docs/en/latest/concepts/annotations.md
Labels: documentation

#1482 docs: add more user cases
  README.md
  powered-by.md
Labels: documentation
