Repository apache/apisix-ingress-controller, pull requests merged in 2022-03, with the labels that each got.

#888 fix json unmarshal error when list plguins
  pkg/apisix/cluster.go
  pkg/apisix/plugin_test.go
Labels: bug

#868 fix: check if stream_routes is disabled
  pkg/apisix/cluster.go
  pkg/apisix/noop.go
  pkg/apisix/stream_route.go
  test/e2e/ingress/sanity.go
  test/e2e/testdata/apisix-stream-disabled.yaml
Labels: bug, triage/accepted

#845 fix: avoid create pluginconfig in the tranlsation of route (#836)
  pkg/ingress/apisix_route.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/apisix_route_test.go
  test/e2e/ingress/resourcepushing.go
Labels: bug

#901 fix: fix up ep resourceVersion comparison and clean up
  pkg/ingress/apisix_tls.go
  pkg/ingress/endpoint.go
  pkg/ingress/endpointslice.go
  pkg/ingress/secret.go
  pkg/ingress/status.go
Labels: bug, area/controller

#893 fix: controller err handler should ignore not found error
  pkg/ingress/apisix_cluster_config.go
  pkg/ingress/apisix_consumer.go
  pkg/ingress/apisix_pluginconfig.go
  pkg/ingress/apisix_route.go
  pkg/ingress/apisix_tls.go
  pkg/ingress/apisix_upstream.go
  pkg/ingress/endpoint.go
  pkg/ingress/endpointslice.go
  pkg/ingress/gateway.go
  pkg/ingress/ingress.go
  pkg/ingress/secret.go
Labels: bug, triage/accepted

#916 chore: upgrade apiVersion from v2beta1 to v2beta3
  docs/en/latest/concepts/apisix_route.md
  docs/en/latest/practices/check-crd-status.md
  docs/en/latest/practices/manage-certificates-with-cert-manager.md
  docs/en/latest/practices/mtls.md
  docs/en/latest/practices/mtls/route.yaml
  docs/en/latest/references/apisix_route_v2beta3.md
Labels: documentation

#925 fix: ApisixRouteEvent type assertion
  pkg/ingress/apisix_route.go
Labels: area/controller

#919 fix: watch all namespaces by default
  pkg/ingress/compare.go
  pkg/ingress/namespace.go
  test/e2e/ingress/namespace.go
  test/e2e/ingress/sanity.go
  test/e2e/scaffold/httpbin.go
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/scaffold.go
Labels: area/controller

#930 docs: remove ApisixRoute v2beta1 & v2alphq1
  docs/en/latest/FAQ.md
  docs/en/latest/concepts/apisix_upstream.md
  docs/en/latest/config.json
  docs/en/latest/design.md
  docs/en/latest/references/apisix_route_v1.md
  docs/en/latest/references/apisix_route_v2alpha1.md
  docs/en/latest/references/apisix_route_v2beta1.md
Labels: documentation

#928 chore: drop v2beta1 api version
  cmd/ingress/ingress.go
  pkg/api/validation/apisix_consumer.go
  pkg/api/validation/apisix_route.go
  pkg/api/validation/apisix_route_test.go
  pkg/api/validation/apisix_tls.go
  pkg/api/validation/apisix_upstream.go
  pkg/config/config.go
  pkg/ingress/apisix_route.go
  pkg/ingress/controller.go
  pkg/ingress/status.go
  pkg/kube/apisix/apis/config/v2beta1/doc.go
  pkg/kube/apisix/apis/config/v2beta1/types.go
  pkg/kube/apisix/apis/config/v2beta1/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v2beta1/zz_generated.register.go
  pkg/kube/apisix/client/clientset/versioned/clientset.go
  pkg/kube/apisix/client/clientset/versioned/fake/clientset_generated.go
  pkg/kube/apisix/client/clientset/versioned/fake/register.go
  pkg/kube/apisix/client/clientset/versioned/scheme/register.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/config_client.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/doc.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/fake/doc.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/fake/fake_apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/fake/fake_config_client.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2beta1/generated_expansion.go
  pkg/kube/apisix/client/informers/externalversions/config/interface.go
  pkg/kube/apisix/client/informers/externalversions/config/v2beta1/apisixroute.go
  pkg/kube/apisix/client/informers/externalversions/config/v2beta1/interface.go
  pkg/kube/apisix/client/informers/externalversions/generic.go
  pkg/kube/apisix/client/listers/config/v2beta1/apisixroute.go
  pkg/kube/apisix/client/listers/config/v2beta1/expansion_generated.go
  pkg/kube/apisix_route.go
  pkg/kube/translation/apisix_route.go
  pkg/kube/translation/translator.go
  pkg/kube/translation/util.go
  policy/base.rego
  samples/deploy/crd/v1/ApisixRoute.yaml
  utils/update-codegen.sh
  utils/verify-codegen.sh
Labels: changelog

#939 feat: introduce v2 apiversion
  pkg/kube/apisix/apis/config/v2/doc.go
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v2/zz_generated.register.go
  pkg/kube/apisix/client/clientset/versioned/clientset.go
  pkg/kube/apisix/client/clientset/versioned/fake/clientset_generated.go
  pkg/kube/apisix/client/clientset/versioned/fake/register.go
  pkg/kube/apisix/client/clientset/versioned/scheme/register.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/apisixclusterconfig.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/apisixconsumer.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/apisixpluginconfig.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/apisixtls.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/apisixupstream.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/config_client.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/doc.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/doc.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixclusterconfig.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixconsumer.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixpluginconfig.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixtls.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixupstream.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_config_client.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/generated_expansion.go
  pkg/kube/apisix/client/informers/externalversions/config/interface.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/apisixclusterconfig.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/apisixconsumer.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/apisixpluginconfig.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/apisixroute.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/apisixtls.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/apisixupstream.go
  pkg/kube/apisix/client/informers/externalversions/config/v2/interface.go
  pkg/kube/apisix/client/informers/externalversions/generic.go
  pkg/kube/apisix/client/listers/config/v2/apisixclusterconfig.go
  pkg/kube/apisix/client/listers/config/v2/apisixconsumer.go
  pkg/kube/apisix/client/listers/config/v2/apisixpluginconfig.go
  pkg/kube/apisix/client/listers/config/v2/apisixroute.go
  pkg/kube/apisix/client/listers/config/v2/apisixtls.go
  pkg/kube/apisix/client/listers/config/v2/apisixupstream.go
  pkg/kube/apisix/client/listers/config/v2/expansion_generated.go
  utils/update-codegen.sh
  utils/verify-codegen.sh
Labels: changelog, area/controller
