Repository apache/apisix-ingress-controller, pull requests merged in 2023-03, with the labels that each got.

#1698 docs: update grpc proxy
  docs/en/latest/tutorials/proxy-grpc-service.md
Labels: documentation

#1519 feat: Add prefer_name into ApisixClusterConfig
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/translation/apisix_cluster_config.go
  pkg/providers/apisix/translation/apisix_cluster_config_test.go
  samples/deploy/crd/v1/ApisixClusterConfig.yaml
  test/e2e/scaffold/cluster_config.go
  test/e2e/suite-features/global_rule.go
Labels: area/controller

#1580 fix: set the health check log level by gin to debug
  pkg/api/server.go
  pkg/log/gin_logger.go
  pkg/log/gin_logger_test.go
Labels: area/controller

#1666 ci: add yamllint rules
  .github/workflows/yamllint-checker.yml
  .yamllint.yml
  Makefile
  samples/deploy/admission/webhook-registration.yaml
  samples/deploy/configmap/apisix-ingress-cm.yaml
  samples/deploy/crd/v1/ApisixConsumer.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  samples/deploy/crd/v1/ApisixTls.yaml
  samples/deploy/crd/v1/ApisixUpstream.yaml
  samples/deploy/deployment/ingress-controller.yaml
  samples/deploy/gateway-api/v0.6.0/experimental-install.yaml
  samples/deploy/gateway-api/v0.6.0/standard-install.yaml
  samples/deploy/rbac/apisix_view_clusterrolebinding.yaml
Labels: CI

#1695 docs: fix typo in aks deployment guide
  docs/en/latest/deployments/azure.md
Labels: documentation

#1700 docs: update the-hard-way.md
  docs/en/latest/tutorials/the-hard-way.md
Labels: documentation

#1538 feat: sync plugin-config labels to apisix
  pkg/providers/apisix/translation/apisix_pluginconfig.go
  test/e2e/suite-chore/consistency.go
Labels: feature, area/controller

#1701 chore(deps): bump github.com/gin-gonic/gin from 1.8.2 to 1.9.0
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies

#1667 docs: using APISIX Ingress as Istio egress gateway
  docs/en/latest/tutorials/istio-egress-gateway
Labels: documentation

#1716 feat: support ingressClass for ApisixPluginConfig
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/apisix_plugin_config.go
  samples/deploy/crd/v1/ApisixPluginConfig.yaml
  test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
Labels: feature, area/controller

#1714 feat: ApisixTls suuport ingressClass
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/apisix/apisix_upstream.go
  samples/deploy/crd/v1/ApisixTls.yaml
  test/e2e/scaffold/ssl.go
  test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
Labels: area/controller

#1717 feat: ApisixConsumer support ingressClass
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/apisix_consumer.go
  samples/deploy/crd/v1/ApisixConsumer.yaml
  test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
Labels: feature, area/controller

#1720 feat: ApisixClusterConfig support IngressClass
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/apisix_cluster_config.go
  samples/deploy/crd/v1/ApisixClusterConfig.yaml
  test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
Labels: feature, area/controller

#1715 bugfix: fix secret created later than apisixtls
  cmd/ingress/ingress.go
  cmd/ingress/ingress_test.go
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/controller.go
  pkg/providers/k8s/endpoint/endpoint.go
  pkg/providers/k8s/endpoint/endpointslice.go
  pkg/providers/k8s/secret.go
  samples/deploy/rbac/apisix_view_clusterrole.yaml
  test/e2e/suite-ingress/suite-ingress-features/secret.go
Labels: bug, area/controller

#1440 feat: Support GatewayAPI route attachment restriction
  go.mod
  go.sum
  pkg/providers/gateway/gateway.go
  pkg/providers/gateway/gateway_class.go
  pkg/providers/gateway/gateway_httproute.go
  pkg/providers/gateway/gateway_tcproute.go
  pkg/providers/gateway/gateway_tlsroute.go
  pkg/providers/gateway/gateway_udproute.go
  pkg/providers/gateway/provider.go
  pkg/providers/gateway/translation/gateway.go
  pkg/providers/gateway/translation/gateway_httproute.go
  pkg/providers/gateway/types/types.go
  pkg/providers/gateway/validator.go
  pkg/providers/k8s/namespace/namespace.go
  pkg/providers/utils/domain.go
  pkg/providers/utils/domain_test.go
  pkg/providers/utils/string.go
  test/e2e/go.sum
  test/e2e/scaffold/ingress.go
  test/e2e/suite-gateway/route_attchment.go
Labels: area/controller, triage/accepted

#1727 ci: Upgrade Ginkgo to latest version
  .github/workflows/e2e-test-ci-v2-cron.yml
  .github/workflows/e2e-test-ci.yml
  .github/workflows/k8s-timer-ci.yml
  Makefile
Labels: CI

#1718 feat: support ingressClass for ApisixGlobalRule
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/apisix_global_rule.go
  samples/deploy/crd/v1/ApisixGlobalRule.yaml
  test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
Labels: feature, area/controller

#593 feat: make multiple controllers handle different ApisixRoute CRDs
  go.mod
  go.sum
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/apisix_route.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
Labels: area/controller

#1745 docs: add tutorial on using custom Plugins
  docs/en/latest/config.json
  docs/en/latest/tutorials/using-custom-plugins.md
Labels: documentation

#1754 fix: missing upstream name in gateway-api routes
  pkg/providers/gateway/translation/gateway_httproute.go
  pkg/providers/gateway/translation/gateway_httproute_test.go
  pkg/providers/gateway/translation/gateway_tlsroute.go
  pkg/providers/gateway/translation/gateway_udproute.go
  pkg/providers/k8s/secret.go
Labels: bug, area/controller

#1758 [cherry-pick] fix: when secret created later than apisixtls it should be updated (#1715)
  cmd/ingress/ingress.go
  cmd/ingress/ingress_test.go
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/controller.go
  pkg/providers/k8s/endpoint/endpoint.go
  pkg/providers/k8s/endpoint/endpointslice.go
  pkg/providers/k8s/secret.go
  samples/deploy/rbac/apisix_view_clusterrole.yaml
  test/e2e/suite-ingress/suite-ingress-features/secret.go
Labels: bug

#1757 [cherry-pick] fix: panic at empty http spec (#1660)
  pkg/providers/ingress/translation/translator.go
  test/e2e/suite-ingress/suite-ingress-resource/ingress.go
Labels: bug

#1756 [cherry-pick] fix: missing upstream name in gateway-api routes (#1754)
  pkg/providers/gateway/translation/gateway_httproute.go
  pkg/providers/gateway/translation/gateway_httproute_test.go
  pkg/providers/gateway/translation/gateway_tlsroute.go
  pkg/providers/gateway/translation/gateway_udproute.go
  pkg/providers/k8s/secret.go
Labels: bug

#1751 docs: added Docker to prerequisite of Installation with Kind
  docs/en/latest/deployments/kind.md
Labels: documentation

#1761 docs: Deploy to OpenShift
  docs/en/latest/deployments/openshift.md
Labels: documentation
