Repository apache/apisix-ingress-controller, pull requests merged in 2023-05, with the labels that each got.

#1832 chore: rename all v2beta3 to v2 in e2e templates
  test/e2e/scaffold/upstream_tls.go
  test/e2e/suite-annotations/plugin_conifg.go
  test/e2e/suite-chore/config.go
  test/e2e/suite-chore/consistency.go
  test/e2e/suite-chore/endpoints.go
  test/e2e/suite-cluster/apisix_cluster_config.go
  test/e2e/suite-features/healthcheck.go
  test/e2e/suite-features/remote_addrs_match.go
  test/e2e/suite-features/retries.go
  test/e2e/suite-features/route_match_exprs.go
  test/e2e/suite-features/scheme.go
  test/e2e/suite-features/subset.go
  test/e2e/suite-features/sync-comparison.go
  test/e2e/suite-features/sync-delay.go
  test/e2e/suite-features/traffic_split.go
  test/e2e/suite-features/websocket.go
  test/e2e/suite-ingress/suite-ingress-features/compare.go
  test/e2e/suite-ingress/suite-ingress-features/resourcesync.go
  test/e2e/suite-ingress/suite-ingress-features/sanity.go
  test/e2e/suite-ingress/suite-ingress-features/secret.go
  test/e2e/suite-ingress/suite-ingress-features/status.go
  test/e2e/suite-ingress/suite-ingress-resource/resourcepushing.go
  test/e2e/suite-ingress/suite-ingress-resource/ssl.go
  test/e2e/suite-ingress/suite-ingress-resource/stream.go
  test/e2e/suite-ingress/suite-ingress-resource/upstream_tls.go
  test/e2e/suite-plugins/suite-plugins-authentication/basic.go
  test/e2e/suite-plugins/suite-plugins-authentication/hmac.go
  test/e2e/suite-plugins/suite-plugins-authentication/jwt.go
  test/e2e/suite-plugins/suite-plugins-authentication/key.go
  test/e2e/suite-plugins/suite-plugins-authentication/wolfrbac.go
  test/e2e/suite-plugins/suite-plugins-general/echo.go
  test/e2e/suite-plugins/suite-plugins-general/redirect.go
  test/e2e/suite-plugins/suite-plugins-other/plugin_config.go
  test/e2e/suite-plugins/suite-plugins-other/serverless.go
  test/e2e/suite-plugins/suite-plugins-security/consumer-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/cors.go
  test/e2e/suite-plugins/suite-plugins-security/csrf.go
  test/e2e/suite-plugins/suite-plugins-security/ip-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/referer-restriction.go
  test/e2e/suite-plugins/suite-plugins-security/uri_blocker.go
  test/e2e/suite-plugins/suite-plugins-traffic/api_breaker.go
  test/e2e/suite-plugins/suite-plugins-traffic/client-control.go
  test/e2e/suite-plugins/suite-plugins-traffic/limit_count.go
  test/e2e/suite-plugins/suite-plugins-traffic/request-validation.go
  test/e2e/suite-plugins/suite-plugins-traffic/request_id.go
  test/e2e/suite-plugins/suite-plugins-transformation/fault_injection.go
  test/e2e/suite-plugins/suite-plugins-transformation/proxy_rewrite.go
  test/e2e/suite-plugins/suite-plugins-transformation/response_rewrite.go
Labels: area/test

#1833 chore(deps): Update dependencies
  go.mod
  go.sum
  pkg/apisix/cluster.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixclusterconfig.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixconsumer.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixglobalrule.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixpluginconfig.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixroute.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixtls.go
  pkg/kube/apisix/client/clientset/versioned/typed/config/v2/fake/fake_apisixupstream.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies

#1841 Update powered-by.md
  powered-by.md
Labels: documentation
