Repository apache/apisix-ingress-controller, pull requests merged in 2023-02, with the labels that each got.

#1636 Update NOTICE
  NOTICE
Labels: documentation

#1641 fix: Add ApisixUpstream CRD status property
  samples/deploy/crd/v1/ApisixUpstream.yaml
  test/e2e/suite-ingress/suite-ingress-features/status.go
Labels: area/helm, area/controller, process/cherry-pick

#1645 docs: fix type of .spec.plugins
  docs/en/latest/concepts/apisix_global_rule.md
Labels: documentation

#1644 Add more types in the pull request template
  .github/PULL_REQUEST_TEMPLATE
Labels: documentation

#1576 fix: fix sync delete svc error
  pkg/providers/ingress/ingress.go
  pkg/providers/ingress/translation/translator.go
  test/e2e/suite-ingress/suite-ingress-resource/ingress.go
Labels: bug, area/controller

#1595 feat: support disable status
  cmd/ingress/ingress.go
  conf/config-default.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/providers/apisix/apisix_cluster_config.go
  pkg/providers/apisix/apisix_consumer.go
  pkg/providers/apisix/apisix_plugin_config.go
  pkg/providers/apisix/apisix_route.go
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/controller.go
  pkg/providers/gateway/gateway.go
  pkg/providers/gateway/provider.go
  pkg/providers/ingress/ingress.go
  pkg/providers/utils/ingress_status.go
  pkg/providers/utils/ingress_status_test.go
  pkg/providers/utils/status.go
  pkg/providers/utils/status_test.go
  test/e2e/scaffold/ingress.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/suite-ingress-features/status.go
Labels: area/controller

#1652 ci: update license-checker
  .github/workflows/license-checker.yml
Labels: area/dependencies

#1660 fix: panic at empty http spec
  pkg/providers/ingress/translation/translator.go
  test/e2e/suite-ingress/suite-ingress-resource/ingress.go
Labels: bug, area/controller

#1633 docs: update the apisix image version and ingress image version
  docs/en/latest/tutorials/the-hard-way.md
Labels: documentation

#1670 docs: small adjustments to Check CRD status tutorial
  docs/en/latest/tutorials/check-crd-status.md
Labels: documentation

#1668 chore(deps): bump golang.org/x/net from 0.5.0 to 0.6.0
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1680 docs: fix jwtAuth configuration error in documents
  docs/en/latest/tutorials/enable-authentication-and-restriction.md
Labels: documentation

#1685 feat: support disable resource periodically sync
  cmd/ingress/ingress.go
  pkg/providers/controller.go
Labels: changelog, area/controller
