Repository apache/apisix-ingress-controller, pull requests merged in 2023-08, with the labels that each got.

#1907 docs: Add QA about exposing gateway as loadbalancer
  docs/en/latest/FAQ.md
Labels: documentation

#1911 ci: auto certs
  Makefile
  test/e2e/scaffold/ssl.go
  test/e2e/suite-features/external-service.go
  test/e2e/suite-ingress/suite-ingress-resource/ssl.go
Labels: CI, area/test

#1840 chore: remove support for Ingress in the extensions/v1beta1 API version
  cmd/ingress/ingress.go
  pkg/config/config.go
  pkg/kube/ingress.go
  pkg/providers/controller.go
  pkg/providers/ingress/ingress.go
  pkg/providers/ingress/ingress_test.go
  pkg/providers/ingress/translation/translator.go
  pkg/providers/utils/ingress_status.go
  pkg/providers/utils/ingress_status_test.go
  test/e2e/suite-annotations/authorization.go
  test/e2e/suite-annotations/cors.go
  test/e2e/suite-annotations/csrf.go
  test/e2e/suite-annotations/forward_auth.go
  test/e2e/suite-annotations/http_method.go
  test/e2e/suite-annotations/iprestriction.go
  test/e2e/suite-annotations/plugin_conifg.go
  test/e2e/suite-annotations/redirect.go
  test/e2e/suite-annotations/response_rewrite.go
  test/e2e/suite-annotations/rewrite.go
  test/e2e/suite-annotations/svc_namespace.go
  test/e2e/suite-annotations/upstreamprotocol.go
  test/e2e/suite-annotations/websocket.go
  test/e2e/suite-chore/consistency.go
  test/e2e/suite-ingress/suite-ingress-resource/ingress.go
Labels: changelog, area/controller

#1788 Chore: Upgrade Go tool chain version 1.19 to version 1.20
  .github/workflows/e2e-test-ci-v2-cron.yml
  .github/workflows/e2e-test-ci.yml
  .github/workflows/goimports-reviser.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/k8s-timer-ci.yml
  .github/workflows/lint-checker.yml
  .github/workflows/unit-test-ci.yml
  .github/workflows/verify-codegen.yml
  Dockerfile
  Makefile
  docs/en/latest/contribute.md
  go.mod
  pkg/utils/s2b.go
  pkg/utils/s2b_old.go
  test/e2e/go.mod
  test/e2e/suite-annotations/redirect.go
Labels: area/dependencies

#1917 chore(deps): bump k8s.io/client-go from 0.27.1 to 0.27.4
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1916 chore: clean up apisix v1
  pkg/kube/apisix/apis/config/v1/doc.go
  pkg/kube/apisix/apis/config/v1/types.go
  pkg/kube/apisix/apis/config/v1/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v1/zz_generated.register.go
Labels: area/controller

#1919 dep: downgraded k8s.io/kube-openapi
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1889 feat: add support for host pass in upstream crd
  docs/en/latest/references/apisix_upstream.md
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/translation/apisix_upstream.go
  pkg/providers/translation/apisix_upstream_test.go
  pkg/types/apisix/v1/types.go
  samples/deploy/crd/v1/ApisixUpstream.yaml
  test/e2e/suite-features/upstream_pass_host.go
Labels: feature, area/controller
