Repository apache/apisix-ingress-controller, pull requests merged in 2023-01, with the labels that each got.

#1581 docs: Update the-hard-way.md
  docs/en/latest/tutorials/the-hard-way.md
Labels: documentation

#1582 docs: add example link.
  docs/en/latest/tutorials/mtls.md
Labels: documentation

#1584 docs: Update the-hard-way.md (#1581)
  docs/en/latest/tutorials/the-hard-way.md
Labels: documentation

#1583 docs: add example link. (#1582)
  docs/en/latest/tutorials/mtls.md
Labels: documentation

#1585 docs: add CHANGELOG for v1.6.0
  CHANGELOG.md
Labels: documentation

#1578 fix: allow passing plugin config name for route with no backends
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/apisix_route_test.go
  test/e2e/suite-plugins/suite-plugins-other/plugin_config.go
Labels: bug, area/controller

#1594 [v1.6 cherry-pick]fix: allow passing plugin config name for route with no backends (#1578)
  pkg/providers/apisix/translation/apisix_route.go
  pkg/providers/apisix/translation/apisix_route_test.go
  test/e2e/suite-plugins/suite-plugins-other/plugin_config.go
Labels: bug, area/controller

#1596 docs: add note about enabling the Plugin
  docs/en/latest/concepts/apisix_route.md
Labels: documentation

#1593 docs: update controller to use adminAPIVersion=v3
  docs/en/latest/deployments/ack.md
  docs/en/latest/deployments/aws.md
  docs/en/latest/deployments/azure.md
  docs/en/latest/deployments/gke.md
  docs/en/latest/deployments/k3s-rke.md
  docs/en/latest/deployments/kind.md
  docs/en/latest/deployments/kubesphere.md
  docs/en/latest/deployments/minikube.md
  docs/en/latest/deployments/tke.md
  docs/en/latest/tutorials/how-to-use-go-plugin-runner-in-apisix-ingress.md
  docs/en/latest/tutorials/manage-certificates-with-cert-manager.md
  docs/en/latest/tutorials/manage-ingress-certificates-with-cert-manager.md
  docs/en/latest/tutorials/proxy-grpc-service.md
Labels: documentation

#1520 chore(deps): bump dependencies from 0.25.4 to 0.26.0
  .golangci.yml
  go.mod
  go.sum
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/kube/apisix/apis/config/v2beta3/zz_generated.deepcopy.go
  pkg/kube/apisix/client/clientset/versioned/clientset.go
  pkg/kube/apisix/client/informers/externalversions/factory.go
  pkg/providers/gateway/gateway.go
  pkg/providers/ingress/ingress.go
  pkg/providers/ingress/translation/annotations/plugins/response_rewrite_test.go
  pkg/providers/ingress/translation/annotations/upstreamscheme/upstreamscheme_test.go
  pkg/providers/utils/ingress_status.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1607 docs: add Gateway API example to the "Getting started" guide
  docs/en/latest/getting-started.md
Labels: documentation

#1603 chore(deps): bump some dependencies
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1606 ci: add goimports-reviser
  .github/workflows/goimports-reviser.yml
  pkg/providers/ingress/translation/annotations/plugins/http_method.go
  pkg/providers/ingress/translation/annotations/plugins/http_method_test.go
  test/e2e/suite-chore/admin_api.go
  test/e2e/suite-features/external-sd.go
  test/e2e/suite-plugins/suite-plugins-general/secret_ref.go
Labels: CI, triage/accepted

#1604 docs: update prowered-by.md
  powered-by.md
Labels: documentation

#1545 feat: add support for filter_func for ApisixRoute
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/types/apisix/v1/types.go
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-features/route_filter_func.go
Labels: feature, area/controller

#1605 doc: add svc-namespace description to the annotations
  docs/en/latest/concepts/annotations.md
Labels: documentation, process/cherry-pick

#1624 [cherry-pick]doc: add svc-namespace description to the annotations (#1605)
  docs/en/latest/concepts/annotations.md
Labels: documentation

#1592 doc: update 1.6 upgrade guide
  docs/en/latest/upgrade.md
Labels: documentation, process/cherry-pick

#1630 docs: using tool auto generate references
  .github/workflows/lint-checker.yml
  docs/en/latest/config.json
  docs/en/latest/references/v2.md
Labels: documentation

#1623 chore: upgrade gateway-api v0.5.1 to v0.6.0
  Makefile
  go.mod
  go.sum
  pkg/providers/gateway/translation/gateway_httproute.go
  samples/deploy/gateway-api/v0.6.0/experimental-install.yaml
  samples/deploy/gateway-api/v0.6.0/standard-install.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1588 add ldap-auth authorization method
  Makefile
  pkg/kube/apisix/apis/config/v2/types.go
  pkg/kube/apisix/apis/config/v2/zz_generated.deepcopy.go
  pkg/providers/apisix/translation/apisix_consumer.go
  pkg/providers/apisix/translation/apisix_consumer_test.go
  pkg/providers/apisix/translation/apisix_plugin.go
  pkg/providers/apisix/translation/apisix_plugin_test.go
  pkg/providers/apisix/translation/apisix_route.go
  pkg/types/apisix/v1/plugin_types.go
  pkg/types/apisix/v1/zz_generated.deepcopy.go
  samples/deploy/crd/v1/ApisixConsumer.yaml
  samples/deploy/crd/v1/ApisixRoute.yaml
  test/e2e/suite-plugins/suite-plugins-authentication/ldap.go
  test/e2e/testdata/ldap/cmd.sh
  test/e2e/testdata/ldap/docker-compose.yaml
Labels: feature, area/controller

#1533 test(e2e): add stream tcp proxy with SNI test
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/suite-ingress-resource/stream.go
Labels: CI
