Repository apache/apisix-ingress-controller, pull requests merged in 2023-04, with the labels that each got.

#1696 docs: add traffic-split plugin usage
  docs/en/latest/plugins/traffic-split.md
Labels: documentation

#1766 docs: Add lost entries of `discovery` in Upstream's reference doc.
  docs/en/latest/references/apisix_upstream.md
Labels: documentation

#1752 docs: add ApisixPluginConfig and update examples
  docs/en/latest/concepts/apisix_plugin_config.md
  docs/en/latest/concepts/apisix_route.md
  docs/en/latest/config.json
Labels: documentation

#1553 feat: sync apisix upstream labels
  pkg/providers/apisix/translation/apisix_upstream.go
  test/e2e/suite-chore/consistency.go
Labels: feature, area/controller

#1769 docs: describe how to generate secret from cert file
  docs/en/latest/tutorials/mtls.md
Labels: documentation

#1772 Fix malformed URL created in schemaClient
  pkg/apisix/schema.go
  pkg/apisix/schema_test.go
Labels: area/controller

#1503 e2e: ingress annotations does not need to use v2beta3
  test/e2e/suite-annotations/svc_namespace.go
Labels: CI, area/test

#1728 feat: CRDs ingressClassName field cannot be modified
  pkg/api/validation/utils.go
  pkg/api/validation/validator.go
  samples/deploy/admission/webhook-registration.yaml
  test/e2e/scaffold/ingress.go
  test/e2e/suite-cluster/apisix_cluster_config.go
  test/e2e/suite-ingress/suite-ingress-features/webhook.go
Labels: area/admission

#1778 chore: use docker buildkit to cache go build cache
  Dockerfile
  Makefile
Labels: CI

#1782 dep: Updated some dependencies.
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: area/dependencies

#1618 refactor: update status
  go.mod
  go.sum
  pkg/kube/apisix_consumer.go
  pkg/kube/apisix_plugin_config.go
  pkg/kube/apisix_route.go
  pkg/kube/apisix_tls.go
  pkg/kube/apisix_upstream.go
  pkg/kube/ingress.go
  pkg/providers/apisix/apisix_consumer.go
  pkg/providers/apisix/apisix_plugin_config.go
  pkg/providers/apisix/apisix_route.go
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/apisix/apisix_upstream.go
  pkg/providers/ingress/ingress.go
  test/e2e/suite-ingress/suite-ingress-features/status.go
Labels: area/controller

#1540 feat: sync consumer crd labels to apisix
  pkg/providers/apisix/translation/apisix_consumer.go
  test/e2e/scaffold/k8s.go
  test/e2e/suite-chore/consistency.go
Labels: feature, area/controller

#1780 fix: secret reference update Ingress
  pkg/providers/apisix/apisix_tls.go
  pkg/providers/ingress/ingress.go
  pkg/providers/ingress/translation/translator.go
  pkg/providers/k8s/namespace/namespace.go
  test/e2e/scaffold/scaffold.go
  test/e2e/suite-ingress/suite-ingress-features/namespace.go
  test/e2e/suite-ingress/suite-ingress-features/secret.go
Labels: area/controller

#1779 fix: health check bug
  pkg/apisix/cluster.go
  pkg/providers/controller.go
Labels: area/controller

#1721 CI: add regression testing with apisix:dev
  .github/workflows/e2e-test-ci-v2-cron-dev.yml
  Makefile
Labels: CI
